// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.pyw",
        "revision": "d3ceb161cfab9e9c5f40a93e15e5be27"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates.py",
        "revision": "2fc7c1c94e2f15173083ebeda834d953"
    },
    {
        "url": "css2",
        "revision": "77a5cee8997a437ea467d4572d76fec2"
    },
    {
        "url": "index.html",
        "revision": "996422bbcb888d49e9a7fcdc1bd7ec77"
    },
    {
        "url": "index2.html",
        "revision": "0a32ee2147d80eca61a5022c357a14ba"
    },
    {
        "url": "manifest.json",
        "revision": "d65bd5f3b88e985913bab5345f4f9b70"
    },
    {
        "url": "newshop.html",
        "revision": "996422bbcb888d49e9a7fcdc1bd7ec77"
    },
    {
        "url": "newshopPOS.html",
        "revision": "05b845f34ad9c307f363038f7ba3a8bb"
    },
    {
        "url": "offline.html",
        "revision": "ad17d01f02bb01615fbc0509f5aee82a"
    },
    {
        "url": "pwa-register.js",
        "revision": "3ec872e4f752840ad8f85922ff6cebe7"
    },
    {
        "url": "sw.js",
        "revision": "eb38867618275f7169bd69e20ce290c4"
    },
    {
        "url": "workbox-window.prod.mjs",
        "revision": "0c782eab9d2e797cbcc39e15c77646c2"
    },
    {
        "url": "xlsx.full.min.js",
        "revision": "31e9848e80e1ddf43c5aa31009cd2b7b"
    },
    {
        "url": "fonts/LhWNMUPbN-oZdNFcBy1-DJYsEoTq5pudQ9L940pGPkB3Qt_-DK0.ttf",
        "revision": "c36c97a3e8b2af5538451cf550693e4a"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}